version: "3.9"

services:
  bsc-geth:
    build:
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/bnb-chain/bsc.git
        GIT_TAG: v1.2.8
    image: bsc-geth:docker-local
