FROM golang:1.19-alpine

ARG GIT_SOURCE
ARG GIT_CHECKOUT_REF

RUN apk add --no-cache make gcc g++ musl-dev linux-headers git jq

RUN cd / && git clone ${GIT_SOURCE} \
    && cd ./bsc && git switch -c ${GIT_CHECKOUT_REF} && make geth \
    && env GO111MODULE=on go run build/ci.go install ./cmd/bootnode

RUN mv /bsc/build/bin/geth /usr/local/bin/
RUN mv /bsc/build/bin/bootnode /usr/local/bin/

EXPOSE 8545 8545/tcp
EXPOSE 30311 30311/udp
