version: "3.9"  # optional since v1.27.0
services:
  relay:
    container_name: relay
    network_mode: "host"
    image: relay:v1.0.0
    volumes:
      - type: bind
        source: ./config
        target: /etc/config
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./keystore
        target: /keystore
    environment:
      - RELAY_CONFIG=/etc/config/config.json
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
